const fs = require('fs'); const path = require('path')
const { Client } = require('pg')
const envRaw = fs.readFileSync('E:/Software/aplikasiku/aistudio/Luxio Project Manager/backend/.env', 'utf8')
const dbUrl = (envRaw.match(/^DATABASE_URL=(.+)$/m) || [])[1].trim()
;(async () => {
  const c = new Client({ connectionString: dbUrl, ssl: { rejectUnauthorized: false } })
  await c.connect()
  const cols = await c.query("SELECT column_name FROM information_schema.columns WHERE table_name='sessions'")
  console.log('sessions cols:', cols.rows.map(r => r.column_name).join(','))
  const s = await c.query("SELECT * FROM sessions WHERE expires_at > NOW() ORDER BY created_at DESC LIMIT 3")
  for (const r of s.rows) console.log('session user=', r.user_id, 'created', r.created_at)
  const cfg = await c.query("SELECT key, length(value::text) vlen FROM owner_config")
  for (const r of cfg.rows) console.log('owner_config:', r.key, 'len', r.vlen)
  await c.end()
})().catch(e => { console.log('ERR', e.message); process.exit(1) })
